/**
 * The inbox doorman: does this inbound email need a reply from us?
 *
 * Two layers, both free at the margin:
 *  1. Rules — what the SENDING system stamps on automated mail: RFC 3834
 *     `Auto-Submitted`, `Precedence: bulk`, `List-Unsubscribe`/`List-Id`,
 *     auto-reply headers, Gmail's own category labels, and no-reply style
 *     sender addresses. No AI, no network.
 *  2. AI — the Haiku call that already writes the inbox summary also answers
 *     "does someone at Off Course need to write back?" (see summarize.ts), so
 *     the second opinion costs nothing extra.
 *
 * The verdict is a LABEL, never a filter: every email stays in the inbox and a
 * human decides (Beer, 2026-10-03: "laat de emails altijd zien … human in the
 * loop"). So combineTriage() is deliberately cautious — it only says 'no' when
 * the AI says so, or when the AI is unsure/unavailable AND a rule independently
 * says the sender is a machine. When the AI sees a real question but a rule
 * says "machine" (a booking platform relaying a guest's question from a
 * no-reply address, say), the answer is 'maybe' — never 'no'.
 *
 * Stored per inbound message in `messages.reply_triage` (migration 169), so a
 * later check can compare each verdict with whether we actually replied.
 */

export type ReplyVerdict = 'yes' | 'no' | 'maybe'

/** Header names (lowercase) the rules layer reads — getMessage() copies exactly these. */
export const TRIAGE_HEADER_NAMES = [
  'auto-submitted',
  'precedence',
  'list-unsubscribe',
  'list-id',
  'x-autoreply',
  'x-autorespond',
  'x-autogenerated',
] as const

/**
 * Gmail's own classifier, for free. CATEGORY_PERSONAL (Primary) is the absence
 * of a signal, not a "human" signal — it's simply not listed. Promotions is
 * already excluded by the sync query; listed anyway so a manual sync with a
 * custom query is judged the same way.
 */
const GMAIL_CATEGORY_SIGNALS: Record<string, string> = {
  CATEGORY_PROMOTIONS: 'gmail:promotions',
  CATEGORY_SOCIAL: 'gmail:social',
  CATEGORY_FORUMS: 'gmail:forums',
  CATEGORY_UPDATES: 'gmail:updates',
}

/**
 * Sender local parts that only machines use. Deliberately narrow: info@,
 * hello@, bookings@ and the like are often typed by real people (including
 * our own suppliers), so they are NOT here.
 */
const MACHINE_LOCAL_PART = /^(no-?reply|do-?not-?reply|donotreply|mailer-daemon|postmaster|bounces?|notifications?|newsletters?|alerts?)([+._-]|$)/i

const BULK_PRECEDENCE = new Set(['bulk', 'junk', 'list', 'auto_reply'])

export interface RuleSignalInput {
  fromEmail: string
  /** Lowercased header name → raw value, only the TRIAGE_HEADER_NAMES that were present. */
  headers?: Record<string, string> | null
  /** Gmail's labelIds for the message. */
  labelIds?: string[] | null
}

/**
 * Every independent sign that a machine sent this. Empty array = no rule
 * fired (which says nothing either way — most real guests send plain mail).
 */
export function detectAutomatedSignals({ fromEmail, headers, labelIds }: RuleSignalInput): string[] {
  const signals: string[] = []
  const h = headers ?? {}

  // RFC 3834: any value other than "no" means an automated sender.
  const autoSubmitted = h['auto-submitted']?.trim().toLowerCase()
  if (autoSubmitted && autoSubmitted !== 'no') signals.push(`auto-submitted:${autoSubmitted.split(/[;\s]/)[0]}`)

  const precedence = h['precedence']?.trim().toLowerCase()
  if (precedence && BULK_PRECEDENCE.has(precedence)) signals.push(`precedence:${precedence}`)

  if (h['list-unsubscribe']?.trim()) signals.push('list-unsubscribe')
  if (h['list-id']?.trim()) signals.push('mailing-list')
  if (h['x-autoreply'] !== undefined || h['x-autorespond'] !== undefined) signals.push('auto-reply')
  if (h['x-autogenerated'] !== undefined) signals.push('auto-generated')

  for (const label of labelIds ?? []) {
    const signal = GMAIL_CATEGORY_SIGNALS[label]
    if (signal) signals.push(signal)
  }

  const localPart = fromEmail.trim().toLowerCase().split('@')[0] ?? ''
  if (MACHINE_LOCAL_PART.test(localPart)) signals.push('no-reply-sender')

  return signals
}

/** The AI half's answer, validated. Anything other than the three verdicts is treated as "no answer". */
export function parseReplyVerdict(value: unknown): ReplyVerdict | null {
  return value === 'yes' || value === 'no' || value === 'maybe' ? value : null
}

export interface AiReplyOpinion {
  verdict: ReplyVerdict
  reason: string | null
}

/** What's stored in messages.reply_triage. `v` lets a future shape change read old rows safely. */
export interface StoredReplyTriage {
  v: 1
  verdict: ReplyVerdict
  /** Which layer(s) the verdict leaned on. 'none' = neither had anything to say → 'maybe'. */
  source: 'rules' | 'ai' | 'rules+ai' | 'none'
  signals: string[]
  ai_verdict: ReplyVerdict | null
  ai_reason: string | null
  at: string
}

/**
 *               | no rule fired | a rule says "machine"
 *  AI yes       | yes           | maybe   (disagreement → a human looks)
 *  AI no        | no            | no
 *  AI maybe     | maybe         | no      (unsure AI, but a machine sent it)
 *  AI missing   | maybe         | no      (Anthropic down — rules alone)
 */
export function combineTriage(signals: string[], ai: AiReplyOpinion | null, now: Date = new Date()): StoredReplyTriage {
  const machine = signals.length > 0
  let verdict: ReplyVerdict
  if (ai?.verdict === 'yes') verdict = machine ? 'maybe' : 'yes'
  else if (ai?.verdict === 'no') verdict = 'no'
  else verdict = machine ? 'no' : 'maybe'

  const source: StoredReplyTriage['source'] = machine && ai ? 'rules+ai' : machine ? 'rules' : ai ? 'ai' : 'none'

  return {
    v: 1,
    verdict,
    source,
    signals,
    ai_verdict: ai?.verdict ?? null,
    ai_reason: ai?.reason ?? null,
    at: now.toISOString(),
  }
}

/**
 * Reads a messages.reply_triage value back from the database. Returns null for
 * anything that isn't a well-formed v1 row, so a malformed or future-shaped
 * value can never crash the inbox — it just shows no label.
 */
export function readReplyTriage(value: unknown): StoredReplyTriage | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null
  const row = value as Record<string, unknown>
  if (row.v !== 1) return null
  const verdict = parseReplyVerdict(row.verdict)
  if (!verdict) return null
  const source = row.source
  return {
    v: 1,
    verdict,
    source: source === 'rules' || source === 'ai' || source === 'rules+ai' || source === 'none' ? source : 'none',
    signals: Array.isArray(row.signals) ? row.signals.filter((s): s is string => typeof s === 'string') : [],
    ai_verdict: parseReplyVerdict(row.ai_verdict),
    ai_reason: typeof row.ai_reason === 'string' ? row.ai_reason : null,
    at: typeof row.at === 'string' ? row.at : '',
  }
}

const SIGNAL_LABELS: Record<string, string> = {
  'list-unsubscribe': 'has an unsubscribe link',
  'mailing-list': 'mailing list',
  'auto-reply': 'auto-reply',
  'auto-generated': 'auto-generated',
  'no-reply-sender': 'no-reply sender',
  'gmail:promotions': 'Gmail: Promotions',
  'gmail:social': 'Gmail: Social',
  'gmail:forums': 'Gmail: Forums',
  'gmail:updates': 'Gmail: Updates',
}

function signalLabel(signal: string): string {
  if (SIGNAL_LABELS[signal]) return SIGNAL_LABELS[signal]
  if (signal.startsWith('auto-submitted:')) return 'automated (Auto-Submitted)'
  if (signal.startsWith('precedence:')) return `bulk mail (${signal.slice('precedence:'.length)})`
  return signal
}

/** What the inbox UI gets — the verdict plus one readable line, never the raw row. */
export interface ReplyTriageView {
  verdict: ReplyVerdict
  reason: string
}

/** Raw messages.reply_triage value → the inbox's view of it, or null when there's nothing valid to show. */
export function toReplyTriageView(value: unknown): ReplyTriageView | null {
  const triage = readReplyTriage(value)
  return triage ? { verdict: triage.verdict, reason: describeReplyTriage(triage) } : null
}

/** One short line for a tooltip/label: why the doorman thinks what it thinks. */
export function describeReplyTriage(triage: StoredReplyTriage): string {
  const parts: string[] = []
  if (triage.ai_reason) parts.push(triage.ai_reason)
  if (triage.signals.length) parts.push([...new Set(triage.signals.map(signalLabel))].join(', '))
  return parts.join(' · ') || 'No clear signal either way'
}
