import { describe, it, expect } from 'vitest'
import { combineTriage, describeReplyTriage, detectAutomatedSignals, parseReplyVerdict, readReplyTriage, toReplyTriageView } from './reply-triage'

const NOW = new Date('2026-10-03T12:00:00.000Z')

describe('detectAutomatedSignals', () => {
  it('finds nothing on a plain guest email', () => {
    expect(detectAutomatedSignals({ fromEmail: 'jane@gmail.com', headers: {}, labelIds: ['INBOX', 'CATEGORY_PERSONAL'] })).toEqual([])
  })

  it('handles missing headers and labels (older callers, failed fetch)', () => {
    expect(detectAutomatedSignals({ fromEmail: 'jane@gmail.com' })).toEqual([])
    expect(detectAutomatedSignals({ fromEmail: 'jane@gmail.com', headers: null, labelIds: null })).toEqual([])
  })

  it('reads RFC 3834 Auto-Submitted, but treats "no" as a human', () => {
    expect(detectAutomatedSignals({ fromEmail: 'x@y.com', headers: { 'auto-submitted': 'auto-generated' } })).toEqual(['auto-submitted:auto-generated'])
    expect(detectAutomatedSignals({ fromEmail: 'x@y.com', headers: { 'auto-submitted': 'auto-replied; owner-email="a@b.c"' } })).toEqual(['auto-submitted:auto-replied'])
    expect(detectAutomatedSignals({ fromEmail: 'x@y.com', headers: { 'auto-submitted': 'No' } })).toEqual([])
  })

  it('flags bulk precedence but not a normal one', () => {
    expect(detectAutomatedSignals({ fromEmail: 'x@y.com', headers: { precedence: 'Bulk' } })).toEqual(['precedence:bulk'])
    expect(detectAutomatedSignals({ fromEmail: 'x@y.com', headers: { precedence: 'first-class' } })).toEqual([])
  })

  it('flags newsletters and mailing lists', () => {
    expect(
      detectAutomatedSignals({ fromEmail: 'news@shop.com', headers: { 'list-unsubscribe': '<mailto:u@shop.com>', 'list-id': '<x.shop.com>' } }),
    ).toEqual(['list-unsubscribe', 'mailing-list'])
  })

  it('ignores an empty List-Unsubscribe header', () => {
    expect(detectAutomatedSignals({ fromEmail: 'x@y.com', headers: { 'list-unsubscribe': '   ' } })).toEqual([])
  })

  it('flags auto-reply headers even when they carry no value', () => {
    expect(detectAutomatedSignals({ fromEmail: 'x@y.com', headers: { 'x-autoreply': '' } })).toEqual(['auto-reply'])
    expect(detectAutomatedSignals({ fromEmail: 'x@y.com', headers: { 'x-autogenerated': 'Reply' } })).toEqual(['auto-generated'])
  })

  it("uses Gmail's category labels", () => {
    expect(detectAutomatedSignals({ fromEmail: 'x@y.com', labelIds: ['INBOX', 'CATEGORY_UPDATES', 'UNREAD'] })).toEqual(['gmail:updates'])
  })

  it('flags machine-only sender addresses', () => {
    for (const from of ['noreply@github.com', 'no-reply@accounts.google.com', 'do-not-reply@x.nl', 'notifications@mail.anthropic.com', 'mailer-daemon@googlemail.com', 'noreply+abc@x.com']) {
      expect(detectAutomatedSignals({ fromEmail: from })).toEqual(['no-reply-sender'])
    }
  })

  it('does NOT flag addresses real people use', () => {
    for (const from of ['info@transrijn.nl', 'hello@buufs.com', 'bookings@hotel.nl', 'noreen@gmail.com', 'alertsmith@x.com']) {
      expect(detectAutomatedSignals({ fromEmail: from })).toEqual([])
    }
  })
})

describe('combineTriage', () => {
  const yes = { verdict: 'yes' as const, reason: 'Guest asks about Saturday' }
  const no = { verdict: 'no' as const, reason: 'Receipt' }
  const maybe = { verdict: 'maybe' as const, reason: null }

  it('AI yes + no rule → yes', () => {
    expect(combineTriage([], yes, NOW)).toMatchObject({ verdict: 'yes', source: 'ai' })
  })

  it('AI yes + machine rule → maybe (disagreement goes to a human, never no)', () => {
    expect(combineTriage(['no-reply-sender'], yes, NOW)).toMatchObject({ verdict: 'maybe', source: 'rules+ai' })
  })

  it('AI no → no, with or without rules', () => {
    expect(combineTriage([], no, NOW)).toMatchObject({ verdict: 'no', source: 'ai' })
    expect(combineTriage(['list-unsubscribe'], no, NOW)).toMatchObject({ verdict: 'no', source: 'rules+ai' })
  })

  it('AI maybe → no only when a rule independently says machine', () => {
    expect(combineTriage([], maybe, NOW).verdict).toBe('maybe')
    expect(combineTriage(['precedence:bulk'], maybe, NOW).verdict).toBe('no')
  })

  it('AI unavailable → rules alone, and unknown stays maybe', () => {
    expect(combineTriage(['auto-submitted:auto-generated'], null, NOW)).toMatchObject({ verdict: 'no', source: 'rules', ai_verdict: null })
    expect(combineTriage([], null, NOW)).toMatchObject({ verdict: 'maybe', source: 'none' })
  })

  it('records everything needed to audit the call later', () => {
    expect(combineTriage(['gmail:updates'], no, NOW)).toEqual({
      v: 1,
      verdict: 'no',
      source: 'rules+ai',
      signals: ['gmail:updates'],
      ai_verdict: 'no',
      ai_reason: 'Receipt',
      at: '2026-10-03T12:00:00.000Z',
    })
  })
})

describe('parseReplyVerdict', () => {
  it('accepts only the three verdicts', () => {
    expect(parseReplyVerdict('yes')).toBe('yes')
    expect(parseReplyVerdict('no')).toBe('no')
    expect(parseReplyVerdict('maybe')).toBe('maybe')
    expect(parseReplyVerdict('Yes')).toBeNull()
    expect(parseReplyVerdict(true)).toBeNull()
    expect(parseReplyVerdict(undefined)).toBeNull()
  })
})

describe('readReplyTriage', () => {
  it('round-trips what combineTriage stores', () => {
    const stored = combineTriage(['list-unsubscribe'], { verdict: 'no', reason: 'Newsletter' }, NOW)
    expect(readReplyTriage(JSON.parse(JSON.stringify(stored)))).toEqual(stored)
  })

  it('returns null for anything malformed instead of throwing', () => {
    for (const bad of [null, undefined, 'no', 42, [], {}, { v: 2, verdict: 'no' }, { v: 1, verdict: 'nope' }]) {
      expect(readReplyTriage(bad)).toBeNull()
    }
  })

  it('tolerates junk in optional fields', () => {
    expect(readReplyTriage({ v: 1, verdict: 'no', source: 'magic', signals: ['a', 3, null], ai_verdict: 'x', ai_reason: 5 })).toEqual({
      v: 1,
      verdict: 'no',
      source: 'none',
      signals: ['a'],
      ai_verdict: null,
      ai_reason: null,
      at: '',
    })
  })
})

describe('toReplyTriageView', () => {
  it('gives the UI a verdict and one readable line', () => {
    const stored = combineTriage(['no-reply-sender'], { verdict: 'no', reason: 'Security alert' }, NOW)
    expect(toReplyTriageView(stored)).toEqual({ verdict: 'no', reason: 'Security alert · no-reply sender' })
  })

  it('is null for rows the doorman never judged', () => {
    expect(toReplyTriageView(null)).toBeNull()
  })
})

describe('describeReplyTriage', () => {
  it('combines the AI reason with readable rule labels, deduplicated', () => {
    const t = combineTriage(['list-unsubscribe', 'precedence:bulk', 'gmail:updates'], { verdict: 'no', reason: 'Marketing newsletter' }, NOW)
    expect(describeReplyTriage(t)).toBe('Marketing newsletter · has an unsubscribe link, bulk mail (bulk), Gmail: Updates')
  })

  it('falls back to a neutral line when nothing is known', () => {
    expect(describeReplyTriage(combineTriage([], null, NOW))).toBe('No clear signal either way')
  })
})
