// Classify a session's referrer as coming from an AI assistant / answer engine.
//
// When an LLM (ChatGPT, Perplexity, Gemini, …) cites Off Course and the user
// clicks through, the browser sends that engine's host as the referrer. This is
// the ONLY first-party signal we have for "AI citations" — the Google Ads API
// knows nothing about it. Pure + table-driven so it's a single source of truth
// (the API route builds its SQL filter from AI_REFERRER_HOSTS) and easy to test.
//
// Known limitation: Google's AI Overviews / AI Mode appear under the normal
// `google.com` referrer, so they can't be separated from organic Google here.

export interface AiEngine {
  key: string
  label: string
}

interface AiEngineDef extends AiEngine {
  /** Referrer hostnames (without leading www.) that map to this engine. */
  hosts: string[]
}

export const AI_ENGINES: AiEngineDef[] = [
  { key: 'chatgpt', label: 'ChatGPT', hosts: ['chatgpt.com', 'chat.openai.com'] },
  { key: 'perplexity', label: 'Perplexity', hosts: ['perplexity.ai'] },
  { key: 'gemini', label: 'Gemini', hosts: ['gemini.google.com', 'bard.google.com'] },
  { key: 'copilot', label: 'Copilot', hosts: ['copilot.microsoft.com'] },
  { key: 'claude', label: 'Claude', hosts: ['claude.ai'] },
  { key: 'meta_ai', label: 'Meta AI', hosts: ['meta.ai'] },
  { key: 'deepseek', label: 'DeepSeek', hosts: ['deepseek.com', 'chat.deepseek.com'] },
  { key: 'grok', label: 'Grok', hosts: ['grok.com', 'x.ai'] },
  { key: 'mistral', label: 'Le Chat (Mistral)', hosts: ['chat.mistral.ai'] },
  { key: 'you', label: 'You.com', hosts: ['you.com'] },
  { key: 'poe', label: 'Poe', hosts: ['poe.com'] },
]

/** Flat list of every AI host — used to build the SQL pre-filter (one source of truth). */
export const AI_REFERRER_HOSTS: string[] = AI_ENGINES.flatMap(e => e.hosts)

/** Extract a normalized hostname (lower-case, no leading www.) from a referrer URL. */
function hostOf(referrer: string): string | null {
  try {
    return new URL(referrer).hostname.toLowerCase().replace(/^www\./, '')
  } catch {
    return null
  }
}

/** Returns the AI engine a referrer belongs to, or null if it isn't an AI engine. */
export function classifyAiReferrer(referrer: string | null | undefined): AiEngine | null {
  if (!referrer) return null
  const host = hostOf(referrer)
  if (!host) return null
  for (const engine of AI_ENGINES) {
    if (engine.hosts.some(h => host === h || host.endsWith(`.${h}`))) {
      return { key: engine.key, label: engine.label }
    }
  }
  return null
}

/**
 * Detect whether an entry page URL carries availability parameters (?date=YYYY-MM-DD or ?time=HH:MM).
 * These deep links are generated by our AI-ready structured data & live availability components.
 */
export function isAvailabilityDeepLink(entryPage: string | null | undefined): boolean {
  if (!entryPage) return false
  return /[?&]date=\d{4}-\d{2}-\d{2}/.test(entryPage) || /[?&]time=\d{1,2}:\d{2}/.test(entryPage)
}

// ── Aggregation (pure) — sessions + bookings per engine ──────────────────────────
// Mirrors the app's existing attribution: a booking belongs to the session it was
// made in (bookings.session_id → analytics_sessions.id), revenue = stripe_amount
// (cents), anonymous visitor ids (anon_*) don't count toward unique visitors.

export interface AiReferralRow {
  key: string
  label: string
  sessions: number
  visitors: number
  bookings: number
  revenueEuros: number
  availabilitySessions: number
  availabilityBookings: number
  availabilityRevenueEuros: number
}

export function aggregateAiReferrals(
  sessions: { id: string; visitor_id: string | null; referrer: string | null; entry_page?: string | null }[],
  bookings: { session_id: string | null; stripe_amount: number | null }[],
): AiReferralRow[] {
  const sessionEngine = new Map<string, AiEngine>()
  const sessionAvailability = new Map<string, boolean>()
  const byEngine = new Map<
    string,
    {
      label: string
      sessions: number
      visitors: Set<string>
      bookings: number
      revenueCents: number
      availabilitySessions: number
      availabilityBookings: number
      availabilityRevenueCents: number
    }
  >()

  for (const s of sessions) {
    const engine = classifyAiReferrer(s.referrer)
    if (!engine) continue
    sessionEngine.set(s.id, engine)
    const isAvail = isAvailabilityDeepLink(s.entry_page)
    sessionAvailability.set(s.id, isAvail)

    let agg = byEngine.get(engine.key)
    if (!agg) {
      agg = {
        label: engine.label,
        sessions: 0,
        visitors: new Set(),
        bookings: 0,
        revenueCents: 0,
        availabilitySessions: 0,
        availabilityBookings: 0,
        availabilityRevenueCents: 0,
      }
      byEngine.set(engine.key, agg)
    }
    agg.sessions++
    if (isAvail) agg.availabilitySessions++
    if (s.visitor_id && !s.visitor_id.startsWith('anon_')) agg.visitors.add(s.visitor_id)
  }

  for (const b of bookings) {
    const engine = b.session_id ? sessionEngine.get(b.session_id) : undefined
    if (!engine) continue
    const agg = byEngine.get(engine.key)
    if (!agg) continue
    agg.bookings++
    const amount = b.stripe_amount ?? 0
    agg.revenueCents += amount

    if (b.session_id && sessionAvailability.get(b.session_id)) {
      agg.availabilityBookings++
      agg.availabilityRevenueCents += amount
    }
  }

  return [...byEngine.entries()]
    .map(([key, a]) => ({
      key,
      label: a.label,
      sessions: a.sessions,
      visitors: a.visitors.size,
      bookings: a.bookings,
      revenueEuros: a.revenueCents / 100,
      availabilitySessions: a.availabilitySessions,
      availabilityBookings: a.availabilityBookings,
      availabilityRevenueEuros: a.availabilityRevenueCents / 100,
    }))
    .sort((x, y) => y.sessions - x.sessions)
}
